version: '3.8'

services:
  influxdb:
    image: influxdb:2.3.0
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana