version: '3.8'

services:
  influxdb:
    image: influxdb:2.3.0
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - monitoring
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin_password
      INFLUXDB_ORG: my-org
      INFLUXDB_BUCKET: playwright

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1
    depends_on:
      - influxdb
    networks:
      - monitoring
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  monitoring:
    driver: bridge
