version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sampledb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
